// <auto-generated />
using Menu.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Menu.Infrastructure.Migrations
{
    [DbContext(typeof(MenuDbContext))]
    [Migration("20260125154620_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Menu.Domain.Entities.Comida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuantasPersonasComen")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Porcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoComidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoComidaId");

                    b.ToTable("Comidas", (string)null);
                });

            modelBuilder.Entity("Menu.Domain.Entities.ComidaIngrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComidaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("ComidaId", "IngredienteId")
                        .IsUnique();

                    b.ToTable("ComidaIngredientes", (string)null);
                });

            modelBuilder.Entity("Menu.Domain.Entities.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Ingredientes", (string)null);
                });

            modelBuilder.Entity("Menu.Domain.Entities.TipoComida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposComida", (string)null);
                });

            modelBuilder.Entity("Menu.Domain.Entities.Comida", b =>
                {
                    b.HasOne("Menu.Domain.Entities.TipoComida", "TipoComida")
                        .WithMany("Comidas")
                        .HasForeignKey("TipoComidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoComida");
                });

            modelBuilder.Entity("Menu.Domain.Entities.ComidaIngrediente", b =>
                {
                    b.HasOne("Menu.Domain.Entities.Comida", "Comida")
                        .WithMany("ComidaIngredientes")
                        .HasForeignKey("ComidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menu.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany("ComidaIngredientes")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comida");

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("Menu.Domain.Entities.Comida", b =>
                {
                    b.Navigation("ComidaIngredientes");
                });

            modelBuilder.Entity("Menu.Domain.Entities.Ingrediente", b =>
                {
                    b.Navigation("ComidaIngredientes");
                });

            modelBuilder.Entity("Menu.Domain.Entities.TipoComida", b =>
                {
                    b.Navigation("Comidas");
                });
#pragma warning restore 612, 618
        }
    }
}
